import * as fs from 'fs';
import mysql from 'mysql2/promise';
import * as dotenv from 'dotenv';
import * as path from 'path';
import { pathToFileURL } from 'url';
import { TableEnum } from '../../interfaces/enums/index';

dotenv.config();

// File information
const enumFileLocation = './src/interfaces/enums/';
const enumFile = 'index.ts';
const outputLocation = './src/interfaces/database/';
const outputFileName = 'TableInterfaces.ts';
const outputFilePath = outputLocation + outputFileName;

// Name generation
const header = `// This file is generated by generateDatabase.ts\nimport * as enums from "../../interfaces/enums";\n\n`;
const Suffix = 'Model' as string;
const SaveSuffix = 'SaveModel' as string;

// #region Database Connection

const databaseName = process.env.DB_NAME as string;

let pool: mysql.Pool;
let connection: mysql.PoolConnection;

// Maak een connectie met de database
async function createDatabaseConnection(): Promise<void> {
    pool = mysql.createPool({
        host: process.env.DB_HOST as string,
        user: process.env.DB_USER as string,
        database: databaseName as string,
        password: process.env.DB_PASSWORD as string,
        port: Number(process.env.DB_PORT) || 3306,
    });
    connection = await pool.getConnection();
}

// #endregion

// #region Table Interfaces

async function generateTableInterfaces(connection: mysql.PoolConnection) {

    // Get all enums from the index.ts file
    const enumPaths = getExportedEnums();
    const enumMapping = await createEnumMapping(enumPaths);

    // Get all tables in the database
    const tablesQuery = `
        SELECT table_name 
        FROM information_schema.tables 
        WHERE table_schema = ?
    `;
    const [tables] = await connection.query(tablesQuery, [databaseName]);

    let interfaceContent = '';

    // Add header
    interfaceContent += header;

    for (const table of tables as any[]) {
        const tableName = table['TABLE_NAME'];

        // Get columns for table
        const columnsQuery = `
            SELECT column_name, data_type 
            FROM information_schema.columns 
            WHERE table_name = ? 
            AND table_schema = ?
        `;
        const [columns] = await connection.query(columnsQuery, [tableName, databaseName]);

        // Generate interface content
        interfaceContent += `export interface ${capitalize(tableName)}${Suffix} {\n`;

        (columns as any[]).forEach((column: any) => {
            interfaceContent += `  ${column.COLUMN_NAME}: ${mapMySQLTypeToTypescript(column.COLUMN_NAME, column.DATA_TYPE, enumMapping)};\n`;
        });

        interfaceContent += `}\n\n`;

        // Generate save models
        interfaceContent += `export interface ${capitalize(tableName)}${SaveSuffix} {\n`;

        (columns as any[]).forEach((column: any) => {
            interfaceContent += `  ${column.COLUMN_NAME}?: ${mapMySQLTypeToTypescript(column.COLUMN_NAME, column.DATA_TYPE, enumMapping)};\n`;
        });

        interfaceContent += `}\n\n`;
    }

    // Write interfaces to file
    fs.writeFileSync(outputFilePath, interfaceContent);

    console.log('Interfaces gegenereerd in ' + outputFilePath);
}

// Translate MySQL types to Typescript types
function mapMySQLTypeToTypescript(columnName: string, mysqlType: string, enumMapping: Record<string, string>): string {
    const lowercaseName = columnName.toLowerCase();

    if (enumMapping[lowercaseName])
        return enumMapping[lowercaseName];

    switch (mysqlType.toLowerCase()) {
        case 'int':
        case 'tinyint':
        case 'smallint':
        case 'mediumint':
        case 'bigint':
        case 'float':
        case 'double':
        case 'decimal':
            return 'number';
        case 'varchar':
        case 'text':
        case 'char':
        case 'tinytext':
        case 'mediumtext':
        case 'longtext':
            return 'string';
        case 'date':
        case 'datetime':
        case 'timestamp':
            return 'Date';
        case 'boolean':
        case 'tinyint(1)':
            return 'boolean';
        default:
            return 'any';
    }
}

// #endregion

// #region Local Enums

function getExportedEnums(): string[] {
    const filePath = path.resolve(enumFileLocation, enumFile);
    const fileContent = fs.readFileSync(filePath, 'utf-8');
    const regex = /export\s*\*\s*from\s*["'](.*?Enum)["']/g;
    const matches = [...fileContent.matchAll(regex)];
    const enumPaths = matches.map(match => `${match[1]}.ts`);
    return enumPaths;
}

async function importEnum(enumPath: string): Promise<Record<string, any>> {
    const resolvedPath = path.resolve(enumFileLocation, enumPath);
    const module = require(resolvedPath);
    return module;
}

async function createEnumMapping(enumPaths: string[]): Promise<Record<string, string>> {
    const enumMapping: Record<string, string> = {};
    for (const enumPath of enumPaths) {
        const enumObject = await importEnum(enumPath);
        for (const enumKey of Object.keys(enumObject)) {
            enumMapping[enumKey.toLowerCase()] = `enums.${enumKey}`;
        }
    }
    return enumMapping;
}

// #endregion

// #region Database Enums

async function updateDatabaseWithEnums(connection: mysql.PoolConnection) {
    // Get all existing enums from 'table_enums'
    const existingEnumsQuery = `
        SELECT id, LOWER(tablename) as tablename FROM table_enums;
    `;
    const [existingEnumRows] = await connection.query(existingEnumsQuery);

    // Create a map of existing enums
    const existingEnumMap = new Map(
        (existingEnumRows as any[]).map((row: any) => [row.tablename, row.id])
    );

    // Loop through all enums in TableEnum
    for (const [tableName, enumValue] of Object.entries(TableEnum)) {
        if (typeof enumValue === 'number') {
            const lowerCaseTableName = tableName.toLowerCase();

            // Check if the enum exists in 'table_enums'
            if (!existingEnumMap.has(lowerCaseTableName)) {
                console.log(`Table '${lowerCaseTableName}' does not exist in 'table_enums'. Adding...`);

                // Add the enum to 'table_enums'
                await connection.query(`
                    INSERT INTO table_enums (Id, TableName)
                    VALUES (?, ?)
                `, [enumValue, lowerCaseTableName]);
            } else {
                console.log(`Table '${lowerCaseTableName}' already exists in 'table_enums' with ID ${existingEnumMap.get(lowerCaseTableName)}.`);
            }
        }
    }
    console.log("All enums checked and added to 'table_enums' where necessary.");
}

// #endregion

// #region Main

// Capitalize first letter of a string and convert snake_case to PascalCase
function capitalize(str: string): string {
    return str
        .split('_')
        .map(word => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
        .join('');
}

async function main() {
    try {
        await createDatabaseConnection();
        await generateTableInterfaces(connection);
        await updateDatabaseWithEnums(connection);
    } catch (err) {
        console.error(err);
    } finally {
        if (connection) {
            connection.release();
        }
        if (pool) {
            await pool.end();
        }
    }
}

main();

// #endregion