export class InterfaceImportManager {
  private static readonly HEADER_BASE = `// This file is generated by generateDatabase.ts\nimport * as enums from "../../interfaces/enums";\nimport { MultiLingualString } from "../../utils/i18n/MultiLangualString";\n`;

  static generateHeader(jsonInterfaceImports: Set<string>): string {
    let header = this.HEADER_BASE;
    
    if (jsonInterfaceImports.size > 0) {
      const imports = Array.from(jsonInterfaceImports).sort().join(', ');
      header += `import { ${imports} } from "../domain";\n`;
    }
    
    header += '\n';
    return header;
  }

  static collectJsonInterfaceImports(
    tables: any[], 
    connection: any, 
    databaseName: string, 
    SchemaUtils: any
  ): Promise<Set<string>> {
    return new Promise(async (resolve) => {
      const jsonInterfaceImports = new Set<string>();

      for (const table of tables) {
        const tableName = table['TABLE_NAME'];
        
        const columnsQuery = `
              SELECT column_name, data_type 
              FROM information_schema.columns 
              WHERE table_name = ? 
              AND table_schema = ?
          `;
        const [columns] = await connection.query(columnsQuery, [tableName, databaseName]);

        (columns as any[]).forEach((column: any) => {
          if (SchemaUtils.isJsonField(column.COLUMN_NAME)) {
            const interfaceName = `${SchemaUtils.capitalize(tableName)}_${SchemaUtils.removeJsonSuffix(column.COLUMN_NAME)}`;
            jsonInterfaceImports.add(interfaceName);
          }
        });
      }

      resolve(jsonInterfaceImports);
    });
  }
} 