import * as fs from 'fs';
import { DatabaseConnection } from './DatabaseConnection';
import { SchemaUtils } from './SchemaUtils';
import Logger from '../application/Logger';

export class StoredProcedureGenerator {
  static async generateRoutineEnums(storedProcedureEnumFilePath: string, functionEnumFilePath: string): Promise<void> {
    const connection = DatabaseConnection.getConnection();
     
    // Get all stored procedures AND functions from the database
    const routinesQuery = `
        SELECT ROUTINE_NAME, ROUTINE_TYPE, ROUTINE_SCHEMA
        FROM information_schema.ROUTINES 
        WHERE ROUTINE_SCHEMA = ? 
        AND ROUTINE_TYPE IN ('PROCEDURE', 'FUNCTION')
        ORDER BY ROUTINE_TYPE, ROUTINE_NAME
    `;
    
    const [routines] = await connection.query(routinesQuery, [DatabaseConnection.databaseName]);

    const procedures = (routines as any[]).filter(r => r.ROUTINE_TYPE === 'PROCEDURE');
    const functions = (routines as any[]).filter(r => r.ROUTINE_TYPE === 'FUNCTION');
    
    // Build StoredProcedureEnum
    let spEnumContent = '// This file is generated by GenerateSchema.ts\n';
    spEnumContent += 'export enum StoredProcedureEnum {\n';

    procedures.forEach((routine: any, index: number) => {
      const routineName = routine.ROUTINE_NAME;
      const enumName = SchemaUtils.convertToPascalCaseEnumName(routineName);
      spEnumContent += `  ${enumName} = "${routineName}"`;
      if (index < procedures.length - 1) spEnumContent += ',';
      spEnumContent += '\n';
    });

    spEnumContent += '}\n';

    // Build FunctionEnum
    let fnEnumContent = '// This file is generated by GenerateSchema.ts\n';
    fnEnumContent += 'export enum FunctionEnum {\n';

    functions.forEach((routine: any, index: number) => {
      const routineName = routine.ROUTINE_NAME;
      const enumName = SchemaUtils.convertToPascalCaseEnumName(routineName);
      fnEnumContent += `  ${enumName} = "${routineName}"`;
      if (index < functions.length - 1) fnEnumContent += ',';
      fnEnumContent += '\n';
    });

    fnEnumContent += '}\n';

    // Write enums to files
    fs.writeFileSync(storedProcedureEnumFilePath, spEnumContent);
    fs.writeFileSync(functionEnumFilePath, fnEnumContent);

    Logger.logInfo(`Stored procedure enum gegenereerd in ${storedProcedureEnumFilePath}`);
    Logger.logInfo(`Function enum gegenereerd in ${functionEnumFilePath}`);
  }
} 