import * as fs from 'fs';
import mysql from 'mysql2/promise';
import { DatabaseConnection } from './DatabaseConnection';
import { SchemaUtils } from './SchemaUtils';

export class StoredProcedureGenerator {
  static async generateStoredProcedureEnum(enumFilePath: string): Promise<void> {
    const connection = DatabaseConnection.getConnection();
    
    // Get all stored procedures from the database
    const storedProceduresQuery = `
        SELECT ROUTINE_NAME 
        FROM information_schema.ROUTINES 
        WHERE ROUTINE_SCHEMA = ? 
        AND ROUTINE_TYPE = 'PROCEDURE'
        ORDER BY ROUTINE_NAME
    `;
    const [storedProcedures] = await connection.query(storedProceduresQuery, [DatabaseConnection.databaseName]);

    let enumContent = '// This file is generated by GenerateSchema.ts\n';
    enumContent += 'export enum StoredProcedureEnum {\n';

    (storedProcedures as any[]).forEach((procedure: any, index: number) => {
      const procedureName = procedure.ROUTINE_NAME;
      const enumName = SchemaUtils.convertToEnumName(procedureName);
      enumContent += `  ${enumName} = "${procedureName}"`;
      
      // Add comma if not the last item
      if (index < (storedProcedures as any[]).length - 1) {
        enumContent += ',';
      }
      enumContent += '\n';
    });

    enumContent += '}\n';

    // Write enum to file
    fs.writeFileSync(enumFilePath, enumContent);

    console.log(`Stored procedure enum gegenereerd in ${enumFilePath}`);
  }
} 