import * as fs from 'fs';
import mysql from 'mysql2/promise';
import { DatabaseConnection } from './DatabaseConnection';
import { SchemaUtils } from './SchemaUtils';
import Logger from '../Logger';

export class TableInterfaceGenerator {
  private static readonly header = `// This file is generated by generateDatabase.ts\nimport * as enums from "../../interfaces/enums";\nimport { MultiLingualString } from "../../utils/i18n/MultiLangualString";\n\n`;
  private static readonly suffix = 'Model' as string;
  private static readonly saveSuffix = 'SaveModel' as string;

  static async generateTableInterfaces(
    outputFilePath: string,
    enumFileLocation: string,
    enumFile: string
  ): Promise<void> {
    const connection = DatabaseConnection.getConnection();
    
    // Get all enums from the index.ts file
    const enumPaths = SchemaUtils.getExportedEnums(enumFileLocation, enumFile);
    const enumMapping = await SchemaUtils.createEnumMapping(enumFileLocation, enumPaths);

    // Get all tables in the database
    const tablesQuery = `
        SELECT table_name 
        FROM information_schema.tables 
        WHERE table_schema = ?
    `;
    const [tables] = await connection.query(tablesQuery, [DatabaseConnection.databaseName]);

    let interfaceContent = '';

    // Add header
    interfaceContent += this.header;

    for (const table of tables as any[]) {
      const tableName = table['TABLE_NAME'];

      // Get columns for table
      const columnsQuery = `
            SELECT column_name, data_type 
            FROM information_schema.columns 
            WHERE table_name = ? 
            AND table_schema = ?
        `;
      const [columns] = await connection.query(columnsQuery, [tableName, DatabaseConnection.databaseName]);

      // Generate interface content
      interfaceContent += `export interface ${SchemaUtils.capitalize(tableName)}${this.suffix} {\n`;

      (columns as any[]).forEach((column: any) => {
        interfaceContent += `  ${SchemaUtils.formatColumnName(column.COLUMN_NAME)}: ${SchemaUtils.mapMySQLTypeToTypescript(column.COLUMN_NAME, column.DATA_TYPE, enumMapping)};\n`;
      });

      interfaceContent += `}\n\n`;

      // Generate save models
      interfaceContent += `export interface ${SchemaUtils.capitalize(tableName)}${this.saveSuffix} {\n`;

      (columns as any[]).forEach((column: any) => {
        interfaceContent += `  ${SchemaUtils.formatColumnName(column.COLUMN_NAME)}?: ${SchemaUtils.mapMySQLTypeToTypescript(column.COLUMN_NAME, column.DATA_TYPE, enumMapping)};\n`;
      });

      interfaceContent += `}\n\n`;
    }

    // Write interfaces to file
    fs.writeFileSync(outputFilePath, interfaceContent);

    Logger.logInfo('Interfaces gegenereerd in ' + outputFilePath);
  }
} 