services:
  app:
    image: ghcr.io/mielvelden/disgames:latest
    restart: unless-stopped
    stop_grace_period: 30s
    env_file:
      - path: .env
        required: false
    environment:
      NODE_ENV: production
    volumes:
      - game_images:/app/images/games
      - mysql_data:/var/lib/mysql

volumes:
  game_images:
  mysql_data:
