services:
  app:
    build: .
    restart: unless-stopped
    command: ["sh", "-c", "npm run deploy && npm start"]
    environment:
      NODE_ENV: production
    volumes:
      - game_images:/app/images/games

  test:
    profiles:
      - test
    build: .
    restart: "no"
    command: ["npm", "run", "test:all"]
    environment:
      NODE_ENV: test

volumes:
  game_images:
