services:
  app:
    build: .
    restart: unless-stopped
    command: ["npm", "start"]
    environment:
      NODE_ENV: production

  test:
    profiles:
      - test
    build: .
    restart: "no"
    command: ["npm", "run", "test:all"]
    environment:
      NODE_ENV: test
