import * as fs from 'fs';
import * as path from 'path';
import { RoutineType, RoutineDefinition, ROUTINE_SUBDIRS, ROUTINE_KEYWORDS } from '../../interfaces/database/RoutineSync';

const ROUTINES_BASE_DIR = path.resolve('./src/db/routines');

export function ensureDirectories(): void {
  for (const subdir of Object.values(ROUTINE_SUBDIRS)) {
    fs.mkdirSync(path.join(ROUTINES_BASE_DIR, subdir), { recursive: true });
  }
}

function buildFileHeader(): string {
  return `-- Generated by db:down`;
}

export function writeRoutineFile(routine: RoutineDefinition): void {
  const subdir = ROUTINE_SUBDIRS[routine.type];
  const filePath = path.join(ROUTINES_BASE_DIR, subdir, `${routine.name}.sql`);
  const content = `${buildFileHeader()}\n${routine.body.trim()}\n`;
  fs.writeFileSync(filePath, content);
}

export function readRoutineFiles(routineType: RoutineType): RoutineDefinition[] {
  const subdir = ROUTINE_SUBDIRS[routineType];
  const dirPath = path.join(ROUTINES_BASE_DIR, subdir);

  if (!fs.existsSync(dirPath))
    return [];

  return fs.readdirSync(dirPath)
    .filter(file => file.endsWith('.sql'))
    .map(file => {
      const filePath = path.join(dirPath, file);
      const body = fs.readFileSync(filePath, 'utf-8');
      const name = file.replace(/\.sql$/, '');
      return { name, type: routineType, body };
    });
}

export function wrapForSync(routine: RoutineDefinition): { drop: string; create: string } {
  const keyword = ROUTINE_KEYWORDS[routine.type];
  const drop = `DROP ${keyword} IF EXISTS \`${routine.name}\``;

  const lines = routine.body.split('\n');
  const createBody = lines
    .filter(line => !line.startsWith('-- '))
    .join('\n')
    .trim();

  return { drop, create: createBody };
}

export function parseCreateBody(row: Record<string, any>): string | null {
  // SHOW CREATE PROCEDURE/FUNCTION always returns the body as the 3rd column (index 2).
  // MySQL returns null here when the DB user lacks SHOW_ROUTINE privilege on this routine.
  const raw = Object.values(row)[2] as string | null | undefined;
  if (!raw)
    return null;

  return raw.replace(/\s*DEFINER\s*=\s*`[^`]*`@`[^`]*`\s*/i, ' ');
}
