// This file is generated by GenerateSchema.ts
export enum StoredProcedureEnum {
  BarChartEventsActivityOverTime = "BarChart_Events_ActivityOverTime",
  BarChartEventsEventsByType = "BarChart_Events_EventsByType",
  BarChartEventsEventsPerHour = "BarChart_Events_EventsPerHour",
  GetRandomGameData = "GetRandomGameData",
  GetUserProfile = "GetUserProfile"
}
