export enum ExceptionEnum {
    GAME_ALREADY_EXISTS = "GAME_ALREADY_EXISTS",
    CHANNEL_OR_SERVER_NOT_FOUND = "CHANNEL_OR_SERVER_NOT_FOUND",
    ANSWER_ALREADY_EXISTS = "ANSWER_ALREADY_EXISTS",
    INVALID_GAME_TYPE = "INVALID_GAME_TYPE",
    WANT_TO_REPLACE_GAME = "WANT_TO_REPLACE_GAME",
    GAME_MODULE_NOT_FOUND = "GAME_MODULE_NOT_FOUND",
    WANT_TO_REPLACE_CHANNEL = "WANT_TO_REPLACE_CHANNEL",
    SAME_USER_ALREADY_ANSWERED = "SAME_USER_ALREADY_ANSWERED",
    WRONG_ANSWER = "WRONG_ANSWER",
    GAME_NOT_ACTIVE = "GAME_NOT_ACTIVE",
    MESSAGE_CHANGE_DISABLED = "MESSAGE_CHANGE_DISABLED",
    INVALID_NUMBER = "INVALID_NUMBER",
}