-- Generated by db:down on 2026-05-03
-- Type: PROCEDURE
CREATE PROCEDURE `BarChart_Events_EventsByType`(
    IN daysBack INT,
    IN serverId INT
)
BEGIN
    SELECT JSON_OBJECT(
        'data',
        JSON_ARRAYAGG(
            JSON_OBJECT(
                'eventType', t.eventTypeKey,
                'count', t.cnt
            )
        ),
        'xAxisKey', 'eventType',
        'valueKeys', JSON_ARRAY('count')
    ) AS ChartDefinition
    FROM
    (
        SELECT
            et.EventTypeEnum,
            et.eventTypeKey,
            COALESCE(ec.cnt, 0) AS cnt
        FROM
            (
                SELECT 1 AS EventTypeEnum, 'SLASH_COMMAND' AS eventTypeKey
                UNION ALL SELECT 2, 'BUTTON'
                UNION ALL SELECT 3, 'SELECT_MENU'
                UNION ALL SELECT 4, 'MODAL_SUBMIT'
                UNION ALL SELECT 5, 'MESSAGE'
                UNION ALL SELECT 6, 'MESSAGE_UPDATE'
                UNION ALL SELECT 7, 'MESSAGE_DELETE'
            ) et
        LEFT JOIN
            (
                SELECT
                    EventTypeEnum,
                    COUNT(*) AS cnt
                FROM events
                WHERE CreatedAt >= (CURDATE() - INTERVAL (daysBack - 1) DAY)
                  AND CreatedAt <  (CURDATE() + INTERVAL 1 DAY)
                  AND (serverId IS NULL OR ServerId = serverId)
                GROUP BY EventTypeEnum
            ) ec
            ON ec.EventTypeEnum = et.EventTypeEnum
        ORDER BY et.EventTypeEnum
    ) t;
END
