-- Generated by db:down
CREATE PROCEDURE `BarChart_Events_EventsPerHour`(
    IN pDaysBack INT
)
BEGIN
    SET SESSION TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

    SELECT JSON_OBJECT(
        'data',
        JSON_ARRAYAGG(
            JSON_OBJECT(
                'hour', t.hourOfDay,
                'count', t.cnt
            )
        ),
        'xAxisKey', 'hour',
        'valueKeys', JSON_ARRAY('count')
    ) AS ChartDefinition
    FROM
    (
        SELECT
            h.hourOfDay,
            COALESCE(e.cnt, 0) AS cnt
        FROM
            (
                SELECT 0  AS hourOfDay UNION ALL SELECT 1  UNION ALL SELECT 2  UNION ALL SELECT 3  UNION ALL SELECT 4
                UNION ALL SELECT 5  UNION ALL SELECT 6  UNION ALL SELECT 7  UNION ALL SELECT 8  UNION ALL SELECT 9
                UNION ALL SELECT 10 UNION ALL SELECT 11 UNION ALL SELECT 12 UNION ALL SELECT 13 UNION ALL SELECT 14
                UNION ALL SELECT 15 UNION ALL SELECT 16 UNION ALL SELECT 17 UNION ALL SELECT 18 UNION ALL SELECT 19
                UNION ALL SELECT 20 UNION ALL SELECT 21 UNION ALL SELECT 22 UNION ALL SELECT 23
            ) h
        LEFT JOIN
            (
                SELECT
                    HOUR(CreatedAt) AS hourOfDay,
                    COUNT(*) AS cnt
                FROM events
                WHERE CreatedAt >= (CURDATE() - INTERVAL (pDaysBack - 1) DAY)
                  AND CreatedAt <  (CURDATE() + INTERVAL 1 DAY)
                GROUP BY HOUR(CreatedAt)
            ) e
            ON e.hourOfDay = h.hourOfDay
        ORDER BY
            h.hourOfDay
    ) t;

    SET SESSION TRANSACTION ISOLATION LEVEL REPEATABLE READ;
END
