-- Generated by db:down
CREATE PROCEDURE `CleanUpData`()
BEGIN
    DECLARE Done INT DEFAULT 0;

    REPEAT
        DELETE FROM events
        WHERE CreatedAt < NOW() - INTERVAL 14 DAY
          AND JSON_UNQUOTE(JSON_EXTRACT(PayloadJSON, '$.channelId')) NOT IN (
              SELECT CAST(ChannelId AS CHAR)
              FROM games
              WHERE ChannelId IS NOT NULL
          )
        LIMIT 500;

        SET Done = ROW_COUNT() < 500;

        DO SLEEP(0.05);

    UNTIL Done END REPEAT;
END
