-- Generated by db:down
CREATE PROCEDURE `CleanUpData`()
BEGIN
    DECLARE Done INT DEFAULT 0;
    DECLARE EventTypeEnumMessage INT DEFAULT 5;

    REPEAT
        DELETE FROM events
        WHERE CreatedAt < NOW() - INTERVAL 21 DAY
          AND EventTypeEnum = EventTypeEnumMessage
        LIMIT 500;

        SET Done = ROW_COUNT() < 500;

        DO SLEEP(0.05);

    UNTIL Done END REPEAT;
END
