-- Generated by db:down
CREATE PROCEDURE `CleanUpMetrics`(IN MinAgeSeconds INT, IN BucketSeconds INT)
BEGIN
    DECLARE Done INT DEFAULT 0;
    DECLARE Cutoff DATETIME;

    SET Cutoff = NOW() - INTERVAL MinAgeSeconds SECOND;

    REPEAT
        DELETE FROM metrics
        WHERE Id IN (
            SELECT Id FROM (
                SELECT Id FROM (
                    SELECT Id,
                           ROW_NUMBER() OVER (
                               PARTITION BY MetricEnum, FLOOR(UNIX_TIMESTAMP(Datetime) / BucketSeconds)
                               ORDER BY Datetime DESC
                           ) AS rn
                    FROM metrics
                    WHERE Datetime < Cutoff
                ) ranked
                WHERE ranked.rn > 1
                LIMIT 500
            ) limited
        );

        SET Done = ROW_COUNT() < 500;

        DO SLEEP(0.05);

    UNTIL Done END REPEAT;
END
