-- Generated by db:down
CREATE PROCEDURE `GetRandomGameData`(
	IN `p_GamesId` INT
)
BEGIN DECLARE v_lang INT;

DECLARE v_gameid INT;

DECLARE v_cnt INT;

DECLARE v_settingsjson JSON;

DECLARE v_limit INT DEFAULT 1;

/* ---------------------------------------------------
     1) Get language, gameTypeEnum and settingsjson
  --------------------------------------------------- */
SELECT s.languageenum,
       g.gametypeenum,
       g.settingsjson INTO v_lang,
                           v_gameid,
                           v_settingsjson
FROM games AS g
JOIN servers AS s ON g.serverid = s.serverid
WHERE g.id = p_gamesid
LIMIT 1;

IF v_lang IS NULL THEN
SELECT CONCAT('Error: Game not found ', p_gamesid) AS errormsg;

ELSE /* ---------------------------------------------------
		       2) Check if game data exists for game + language
		    --------------------------------------------------- */ IF v_gameid = 9 THEN
SET v_limit = 4;

END IF;


SELECT COUNT(*) INTO v_cnt
FROM game_data AS gd
WHERE gd.gameid = v_gameid
  AND JSON_CONTAINS_PATH(gd.responsemls, 'one', CONCAT('$.\"', v_lang, '\"'));

IF v_cnt = 0 THEN
SELECT CONCAT('Error: No game data for ', v_gameid, ' with language ', v_lang) AS errormsg;

ELSE /* ---------------------------------------------------
		         3) Get random data with datasheet filtering
		      --------------------------------------------------- */
SELECT DISTINCT gd.id,
                gd.messagemls,
                gd.responsemls
FROM game_data AS gd
LEFT JOIN JSON_TABLE(v_settingsjson, '$.datasheets[*]' COLUMNS (datasheet_id INT PATH '$')) ds ON gd.DatasheetId = ds.datasheet_id
WHERE gd.gameid = v_gameid
  AND JSON_CONTAINS_PATH(gd.responsemls, 'one', CONCAT('$.\"', v_lang, '\"'))
  AND (gd.DatasheetId IS NULL
       OR ds.datasheet_id IS NOT NULL)
ORDER BY RAND()
LIMIT v_limit;

END IF;

END IF;

END
