-- Generated by db:down
CREATE PROCEDURE `GetTopUsersByExperience`(
	IN `p_Limit` INT
)
BEGIN
SELECT u.UserId,
       u.Username,
       u.ExperiencePoints
FROM users u
WHERE u.UserRoleEnum != 2
ORDER BY u.ExperiencePoints DESC
LIMIT p_Limit;
END
