-- Generated by db:down
CREATE PROCEDURE `GetTopServersByPoints`(
	IN `p_Limit` INT
)
BEGIN
SELECT s.ServerId,
       s.Name,
       s.LanguageEnum,
       s.MemberCount,
       COALESCE(SUM(p.Points), 0) AS TotalPoints
FROM servers s
LEFT JOIN points p ON p.ServerId = s.ServerId
GROUP BY s.Id, s.ServerId, s.Name, s.LanguageEnum, s.MemberCount
ORDER BY TotalPoints DESC
LIMIT p_Limit;
END
