-- Generated by db:down
CREATE PROCEDURE `GetUserProfile`(
    IN p_UserId BIGINT
)
BEGIN
    WITH TotalPoints AS (
        SELECT 
            p.UserId,
            SUM(p.Points) AS TotalPoints
        FROM points p
        GROUP BY p.UserId
    ),
    Ranked AS (
        SELECT 
            tp.UserId,
            tp.TotalPoints,
            RANK() OVER (ORDER BY tp.TotalPoints DESC) AS UserRank
        FROM TotalPoints tp
    )
    SELECT 
        u.UserId,
        u.Username,
        u.UserRoleEnum,
        COALESCE(r.TotalPoints, 0) AS TotalPoints,
        COALESCE(r.UserRank, (SELECT COUNT(*) FROM TotalPoints)) AS UserRank,
        (SELECT COUNT(*) FROM users) AS TotalUsers
    FROM users u
    LEFT JOIN Ranked r ON u.UserId = r.UserId
    WHERE u.UserId = p_UserId;
END
