-- Generated by db:down
CREATE PROCEDURE `LineChart_Server_NewServer`(
	IN `daysBack` INT
)
BEGIN
	SET SESSION TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

	WITH RECURSIVE day_seq AS (
		SELECT 0 AS n
		UNION ALL
		SELECT n + 1 FROM day_seq WHERE n < daysBack - 1
	)
	SELECT JSON_OBJECT(
		'data',
		JSON_ARRAYAGG(
			JSON_OBJECT(
				'day', t.dayStr,
				'servers', t.total
			)
		),
		'xAxisKey', 'day',
		'valueKeys', JSON_ARRAY('servers')
	) AS ChartDefinition
	FROM
	(
		SELECT
			d.dayDate,
			DATE_FORMAT(d.dayDate, '%Y-%m-%d') AS dayStr,
			(
				SELECT m.Value
				FROM metrics m
				WHERE m.MetricEnum = 2
				  AND m.Datetime <= d.dayDate + INTERVAL 1 DAY - INTERVAL 1 SECOND
				ORDER BY m.Datetime DESC
				LIMIT 1
			) AS total
		FROM
		(
			SELECT DATE_SUB(CURDATE(), INTERVAL n DAY) AS dayDate
			FROM day_seq
		) d
		ORDER BY d.dayDate
	) t;

	SET SESSION TRANSACTION ISOLATION LEVEL REPEATABLE READ;
END
