-- Generated by db:down on 2026-05-03
-- Type: PROCEDURE
CREATE PROCEDURE `PieChart_Server_LanguageDistribution`()
BEGIN
    SELECT JSON_OBJECT(
        'xAxisKey', 'language',
        'valueKeys', JSON_ARRAY('value'),
        'data', (
            SELECT JSON_ARRAYAGG(
                JSON_OBJECT(
                    'language', s.LanguageEnum,
                    'label',    CASE s.LanguageEnum
                                    WHEN 1 THEN 'English'
                                    WHEN 2 THEN 'Dutch'
                                    WHEN 3 THEN 'Spanish'
                                    WHEN 4 THEN 'German'
                                    ELSE CONCAT('Language ', s.LanguageEnum)
                                END,
                    'value',    s.cnt
                )
            )
            FROM (
                SELECT LanguageEnum, COUNT(*) AS cnt
                FROM servers
                GROUP BY LanguageEnum
                ORDER BY LanguageEnum ASC
            ) s
        )
    ) AS ChartDefinition;
END
