-- Generated by db:down on 2026-05-03
-- Type: PROCEDURE
CREATE PROCEDURE `PieChart_Games_GamesByType`(
    IN serverId INT
)
BEGIN
    SELECT JSON_OBJECT(
        'xAxisKey', 'gameType',
        'valueKeys', JSON_ARRAY('value'),
        'data',
        JSON_ARRAYAGG(
            JSON_OBJECT(
                'gameType', t.gameName,
                'label',    t.gameName,
                'value',    t.cnt
            )
        )
    ) AS ChartDefinition
    FROM
    (
        SELECT
            gt.Id,
            gt.gameName,
            COALESCE(gc.cnt, 0) AS cnt
        FROM game_types gt
        LEFT JOIN
            (
                SELECT
                    GameTypeEnum,
                    COUNT(*) AS cnt
                FROM games
                WHERE (serverId IS NULL OR ServerId = serverId)
                GROUP BY GameTypeEnum
            ) gc
            ON gc.GameTypeEnum = gt.Id
        ORDER BY gt.Id
    ) t;
END
