-- Generated by db:down
CREATE FUNCTION `GetDisplayName`(
    TableEnum INT,
    ObjectId INT
) RETURNS varchar(255) CHARSET utf8mb4
    READS SQL DATA
BEGIN
    DECLARE displayValue VARCHAR(255);

    DECLARE TableEnumServers INT DEFAULT 1;
    DECLARE TableEnumGames INT DEFAULT 2;
    DECLARE TableEnumGameData INT DEFAULT 3;
    DECLARE TableEnumPoints INT DEFAULT 4;
    DECLARE TableEnumUsers INT DEFAULT 5;
    DECLARE TableEnumDatasheets INT DEFAULT 6;
    DECLARE TableEnumGamesXDatasheets INT DEFAULT 7;
    DECLARE TableEnumTimelineEntries INT DEFAULT 8;

    CASE TableEnum
        WHEN TableEnumServers THEN
            SELECT Name
              INTO displayValue
              FROM servers
             WHERE Id = ObjectId
             LIMIT 1;

        WHEN TableEnumGames THEN
            SELECT CONCAT(CAST(ServerId AS CHAR), ' ', CAST(ChannelId AS CHAR))
              INTO displayValue
              FROM games
             WHERE Id = ObjectId
             LIMIT 1;

        WHEN TableEnumUsers THEN
            SELECT Username
              INTO displayValue
              FROM users
             WHERE Id = ObjectId
             LIMIT 1;

        ELSE
            SET displayValue = NULL;
    END CASE;

    RETURN displayValue;
END
