// This file is generated by generateDatabase.ts
import * as enums from "../../interfaces/enums";
import { MultiLingualString } from "../../utils/i18n/MultiLingualString";
import { Debug_Data, Events_Payload, Games_Settings, Metrics_Metrics, TimelineEntries_Changes } from "../domain";

export interface DatasheetsModel {
  Id: number;
  LanguageEnum: enums.LanguageEnum;
  Name: string;
  ServerId: number;
}

export enum DatasheetsModelFieldEnum {
  Id = "Id",
  LanguageEnum = "LanguageEnum",
  Name = "Name",
  ServerId = "ServerId"
}

export interface DatasheetsSaveModel {
  Id?: number;
  LanguageEnum?: enums.LanguageEnum;
  Name?: string;
  ServerId?: number;
}

export interface DebugModel {
  CreatedAt: Date;
  Data: Debug_Data;
  Id: number;
  ServerId: number;
  UniqueCode: string;
  UpdatedAt: Date;
}

export enum DebugModelFieldEnum {
  CreatedAt = "CreatedAt",
  Data = "Data",
  Id = "Id",
  ServerId = "ServerId",
  UniqueCode = "UniqueCode",
  UpdatedAt = "UpdatedAt"
}

export interface DebugSaveModel {
  CreatedAt?: Date;
  DataJSON?: Debug_Data;
  Id?: number;
  ServerId?: number;
  UniqueCode?: string;
  UpdatedAt?: Date;
}

export interface EventsModel {
  CreatedAt: Date;
  EventTypeEnum: enums.EventTypeEnum;
  Id: number;
  Payload: Events_Payload;
  ServerId: number;
  UserId: number;
}

export enum EventsModelFieldEnum {
  CreatedAt = "CreatedAt",
  EventTypeEnum = "EventTypeEnum",
  Id = "Id",
  Payload = "Payload",
  ServerId = "ServerId",
  UserId = "UserId"
}

export interface EventsSaveModel {
  CreatedAt?: Date;
  EventTypeEnum?: enums.EventTypeEnum;
  Id?: number;
  PayloadJSON?: Events_Payload;
  ServerId?: number;
  UserId?: number;
}

export interface GameDataModel {
  DataSheetId: number;
  GameId: number;
  Id: number;
  Message: MultiLingualString;
  Response: MultiLingualString;
}

export enum GameDataModelFieldEnum {
  DataSheetId = "DataSheetId",
  GameId = "GameId",
  Id = "Id",
  Message = "Message",
  Response = "Response"
}

export interface GameDataSaveModel {
  DataSheetId?: number;
  GameId?: number;
  Id?: number;
  Message?: MultiLingualString;
  Response?: MultiLingualString;
}

export interface GameTypesModel {
  allowMessageChange: number;
  description: number;
  gameDisabled: number;
  gameName: string;
  gameRules: number;
  Id: number;
  pointPerGame: number;
  replyMessage: number;
  sameUserAllowed: number;
}

export enum GameTypesModelFieldEnum {
  allowMessageChange = "allowMessageChange",
  description = "description",
  gameDisabled = "gameDisabled",
  gameName = "gameName",
  gameRules = "gameRules",
  Id = "Id",
  pointPerGame = "pointPerGame",
  replyMessage = "replyMessage",
  sameUserAllowed = "sameUserAllowed"
}

export interface GameTypesSaveModel {
  allowMessageChange?: number;
  description?: number;
  gameDisabled?: number;
  gameName?: string;
  gameRules?: number;
  Id?: number;
  pointPerGame?: number;
  replyMessage?: number;
  sameUserAllowed?: number;
}

export interface GamesModel {
  Answer: string;
  ChannelId: string;
  GameTypeEnum: enums.GameTypeEnum;
  Id: number;
  LastUser: string;
  MessageId: string;
  ServerId: string;
  Settings: Games_Settings;
}

export enum GamesModelFieldEnum {
  Answer = "Answer",
  ChannelId = "ChannelId",
  GameTypeEnum = "GameTypeEnum",
  Id = "Id",
  LastUser = "LastUser",
  MessageId = "MessageId",
  ServerId = "ServerId",
  Settings = "Settings"
}

export interface GamesSaveModel {
  Answer?: string;
  ChannelId?: string;
  GameTypeEnum?: enums.GameTypeEnum;
  Id?: number;
  LastUser?: string;
  MessageId?: string;
  ServerId?: string;
  SettingsJSON?: Games_Settings;
}

export interface GamesXDatasheetsModel {
  DatasheetId: number;
  GameId: number;
  Id: number;
}

export enum GamesXDatasheetsModelFieldEnum {
  DatasheetId = "DatasheetId",
  GameId = "GameId",
  Id = "Id"
}

export interface GamesXDatasheetsSaveModel {
  DatasheetId?: number;
  GameId?: number;
  Id?: number;
}

export interface LanguageModel {
  EN: string;
  ES: string;
  GE: string;
  Id: number;
  NL: string;
}

export enum LanguageModelFieldEnum {
  EN = "EN",
  ES = "ES",
  GE = "GE",
  Id = "Id",
  NL = "NL"
}

export interface LanguageSaveModel {
  EN?: string;
  ES?: string;
  GE?: string;
  Id?: number;
  NL?: string;
}

export interface MetricsModel {
  Date: Date;
  Id: number;
  Metrics: Metrics_Metrics;
}

export enum MetricsModelFieldEnum {
  Date = "Date",
  Id = "Id",
  Metrics = "Metrics"
}

export interface MetricsSaveModel {
  Date?: Date;
  Id?: number;
  MetricsJSON?: Metrics_Metrics;
}

export interface PointsModel {
  GameId: number;
  Id: number;
  Points: number;
  ServerId: string;
  UserId: string;
}

export enum PointsModelFieldEnum {
  GameId = "GameId",
  Id = "Id",
  Points = "Points",
  ServerId = "ServerId",
  UserId = "UserId"
}

export interface PointsSaveModel {
  GameId?: number;
  Id?: number;
  Points?: number;
  ServerId?: string;
  UserId?: string;
}

export interface ServersModel {
  Id: number;
  LanguageEnum: enums.LanguageEnum;
  Name: string;
  Points: number;
  ServerId: string;
}

export enum ServersModelFieldEnum {
  Id = "Id",
  LanguageEnum = "LanguageEnum",
  Name = "Name",
  Points = "Points",
  ServerId = "ServerId"
}

export interface ServersSaveModel {
  Id?: number;
  LanguageEnum?: enums.LanguageEnum;
  Name?: string;
  Points?: number;
  ServerId?: string;
}

export interface StatisticsModel {
  Date: Date;
  GameId: number;
  Id: number;
  Value: number;
}

export enum StatisticsModelFieldEnum {
  Date = "Date",
  GameId = "GameId",
  Id = "Id",
  Value = "Value"
}

export interface StatisticsSaveModel {
  Date?: Date;
  GameId?: number;
  Id?: number;
  Value?: number;
}

export interface TableEnumsModel {
  Id: number;
  TableName: string;
}

export enum TableEnumsModelFieldEnum {
  Id = "Id",
  TableName = "TableName"
}

export interface TableEnumsSaveModel {
  Id?: number;
  TableName?: string;
}

export interface TimelineEntriesModel {
  Changes: TimelineEntries_Changes;
  CreatedAt: Date;
  Id: number;
  ObjectId: number;
  ServerId: number;
  TableEnum: enums.TableEnum;
  TimelineType: number;
  UserId: number;
}

export enum TimelineEntriesModelFieldEnum {
  Changes = "Changes",
  CreatedAt = "CreatedAt",
  Id = "Id",
  ObjectId = "ObjectId",
  ServerId = "ServerId",
  TableEnum = "TableEnum",
  TimelineType = "TimelineType",
  UserId = "UserId"
}

export interface TimelineEntriesSaveModel {
  ChangesJSON?: TimelineEntries_Changes;
  CreatedAt?: Date;
  Id?: number;
  ObjectId?: number;
  ServerId?: number;
  TableEnum?: enums.TableEnum;
  TimelineType?: number;
  UserId?: number;
}

export interface UsersModel {
  CreatedAt: Date;
  Id: number;
  OAuth2AccessToken: string;
  UserId: string;
  Username: string;
  UserRoleEnum: enums.UserRoleEnum;
}

export enum UsersModelFieldEnum {
  CreatedAt = "CreatedAt",
  Id = "Id",
  OAuth2AccessToken = "OAuth2AccessToken",
  UserId = "UserId",
  Username = "Username",
  UserRoleEnum = "UserRoleEnum"
}

export interface UsersSaveModel {
  CreatedAt?: Date;
  Id?: number;
  OAuth2AccessToken?: string;
  UserId?: string;
  Username?: string;
  UserRoleEnum?: enums.UserRoleEnum;
}

