// This file is generated by generateDatabase.ts
import * as enums from "../../interfaces/enums";
import { MultiLingualString } from "../../utils/i18n/MultiLingualString";
import { Debug_Data, Events_Payload, Games_Settings, Metrics_Metrics, TimelineEntries_Changes } from "../domain";

import { BaseEntityClass } from '../../utils/database/BaseEntityClass';
import { BaseEntity, BaseEntityFieldType } from '../../interfaces/database/BaseEntity';

export interface DatasheetsModel {
  Description: MultiLingualString;
  Id: number;
  Name: MultiLingualString;
  ServerId: number;
}

export enum DatasheetsModelFieldEnum {
  Description = "Description",
  Id = "Id",
  Name = "Name",
  ServerId = "ServerId"
}

export function getDatasheetsFieldType(field: DatasheetsModelFieldEnum): BaseEntityFieldType {
  switch (field) {
    case DatasheetsModelFieldEnum.Description:
      return BaseEntityFieldType.MultiLingualString;
    case DatasheetsModelFieldEnum.Id:
      return BaseEntityFieldType.Number;
    case DatasheetsModelFieldEnum.Name:
      return BaseEntityFieldType.MultiLingualString;
    case DatasheetsModelFieldEnum.ServerId:
      return BaseEntityFieldType.Number;
  }
}

export class DatasheetsModel extends BaseEntityClass<DatasheetsModelFieldEnum> implements DatasheetsModel {
  protected static fieldEnum = DatasheetsModelFieldEnum;
  protected static tableEnum = enums.TableEnum.DATASHEETS;

  Description: MultiLingualString;
  Name: MultiLingualString;
  ServerId: number;

  constructor(data: Partial<DatasheetsModel>) {
    super(data as BaseEntity);
    this.Description = data.Description!;
    this.Id = data.Id!;
    this.Name = data.Name!;
    this.ServerId = data.ServerId!;
  }
}

export interface DatasheetsSaveModel {
  Description?: MultiLingualString;
  Id?: number;
  Name?: MultiLingualString;
  ServerId?: number;
}

export class DatasheetsSaveModel extends BaseEntityClass<DatasheetsModelFieldEnum> implements DatasheetsSaveModel {
  protected static fieldEnum = DatasheetsModelFieldEnum;
  protected static tableEnum = enums.TableEnum.DATASHEETS;

  Description?: MultiLingualString;
  Name?: MultiLingualString;
  ServerId?: number;

  constructor(data: Partial<DatasheetsSaveModel>) {
    super({ Id: data.Id ?? 0 });
    if (data.Description !== undefined) this.Description = data.Description;
    if (data.Id !== undefined) this.Id = data.Id;
    if (data.Name !== undefined) this.Name = data.Name;
    if (data.ServerId !== undefined) this.ServerId = data.ServerId;
  }
}

export interface DebugModel {
  CreatedAt: Date;
  Data: Debug_Data;
  Id: number;
  ServerId: number;
  UniqueCode: string;
  UpdatedAt: Date;
}

export enum DebugModelFieldEnum {
  CreatedAt = "CreatedAt",
  Data = "Data",
  Id = "Id",
  ServerId = "ServerId",
  UniqueCode = "UniqueCode",
  UpdatedAt = "UpdatedAt"
}

export function getDebugFieldType(field: DebugModelFieldEnum): BaseEntityFieldType {
  switch (field) {
    case DebugModelFieldEnum.CreatedAt:
      return BaseEntityFieldType.Date;
    case DebugModelFieldEnum.Data:
      return BaseEntityFieldType.Json;
    case DebugModelFieldEnum.Id:
      return BaseEntityFieldType.Number;
    case DebugModelFieldEnum.ServerId:
      return BaseEntityFieldType.Number;
    case DebugModelFieldEnum.UniqueCode:
      return BaseEntityFieldType.String;
    case DebugModelFieldEnum.UpdatedAt:
      return BaseEntityFieldType.Date;
  }
}

export class DebugModel extends BaseEntityClass<DebugModelFieldEnum> implements DebugModel {
  protected static fieldEnum = DebugModelFieldEnum;
  protected static tableEnum = enums.TableEnum.DEBUG;

  CreatedAt: Date;
  Data: Debug_Data;
  ServerId: number;
  UniqueCode: string;
  UpdatedAt: Date;

  constructor(data: Partial<DebugModel>) {
    super(data as BaseEntity);
    this.CreatedAt = data.CreatedAt!;
    this.Data = data.Data!;
    this.Id = data.Id!;
    this.ServerId = data.ServerId!;
    this.UniqueCode = data.UniqueCode!;
    this.UpdatedAt = data.UpdatedAt!;
  }
}

export interface DebugSaveModel {
  CreatedAt?: Date;
  DataJSON?: Debug_Data;
  Id?: number;
  ServerId?: number;
  UniqueCode?: string;
  UpdatedAt?: Date;
}

export class DebugSaveModel extends BaseEntityClass<DebugModelFieldEnum> implements DebugSaveModel {
  protected static fieldEnum = DebugModelFieldEnum;
  protected static tableEnum = enums.TableEnum.DEBUG;
  protected static fieldToPropertyMap: Record<string, string> = { Data: "DataJSON" };

  CreatedAt?: Date;
  DataJSON?: Debug_Data;
  ServerId?: number;
  UniqueCode?: string;
  UpdatedAt?: Date;

  constructor(data: Partial<DebugSaveModel>) {
    super({ Id: data.Id ?? 0 });
    if (data.CreatedAt !== undefined) this.CreatedAt = data.CreatedAt;
    if (data.DataJSON !== undefined) this.DataJSON = data.DataJSON;
    if (data.Id !== undefined) this.Id = data.Id;
    if (data.ServerId !== undefined) this.ServerId = data.ServerId;
    if (data.UniqueCode !== undefined) this.UniqueCode = data.UniqueCode;
    if (data.UpdatedAt !== undefined) this.UpdatedAt = data.UpdatedAt;
  }
}

export interface EventsModel {
  CreatedAt: Date;
  EventTypeEnum: enums.EventTypeEnum;
  Id: number;
  Payload: Events_Payload;
  ServerId: number;
  UserId: number;
}

export enum EventsModelFieldEnum {
  CreatedAt = "CreatedAt",
  EventTypeEnum = "EventTypeEnum",
  Id = "Id",
  Payload = "Payload",
  ServerId = "ServerId",
  UserId = "UserId"
}

export function getEventsFieldType(field: EventsModelFieldEnum): BaseEntityFieldType {
  switch (field) {
    case EventsModelFieldEnum.CreatedAt:
      return BaseEntityFieldType.Date;
    case EventsModelFieldEnum.EventTypeEnum:
      return BaseEntityFieldType.Enum;
    case EventsModelFieldEnum.Id:
      return BaseEntityFieldType.Number;
    case EventsModelFieldEnum.Payload:
      return BaseEntityFieldType.Json;
    case EventsModelFieldEnum.ServerId:
      return BaseEntityFieldType.Number;
    case EventsModelFieldEnum.UserId:
      return BaseEntityFieldType.Number;
  }
}

export class EventsModel extends BaseEntityClass<EventsModelFieldEnum> implements EventsModel {
  protected static fieldEnum = EventsModelFieldEnum;
  protected static tableEnum = enums.TableEnum.EVENTS;

  CreatedAt: Date;
  EventTypeEnum: enums.EventTypeEnum;
  Payload: Events_Payload;
  ServerId: number;
  UserId: number;

  constructor(data: Partial<EventsModel>) {
    super(data as BaseEntity);
    this.CreatedAt = data.CreatedAt!;
    this.EventTypeEnum = data.EventTypeEnum!;
    this.Id = data.Id!;
    this.Payload = data.Payload!;
    this.ServerId = data.ServerId!;
    this.UserId = data.UserId!;
  }
}

export interface EventsSaveModel {
  CreatedAt?: Date;
  EventTypeEnum?: enums.EventTypeEnum;
  Id?: number;
  PayloadJSON?: Events_Payload;
  ServerId?: number;
  UserId?: number;
}

export class EventsSaveModel extends BaseEntityClass<EventsModelFieldEnum> implements EventsSaveModel {
  protected static fieldEnum = EventsModelFieldEnum;
  protected static tableEnum = enums.TableEnum.EVENTS;
  protected static fieldToPropertyMap: Record<string, string> = { Payload: "PayloadJSON" };

  CreatedAt?: Date;
  EventTypeEnum?: enums.EventTypeEnum;
  PayloadJSON?: Events_Payload;
  ServerId?: number;
  UserId?: number;

  constructor(data: Partial<EventsSaveModel>) {
    super({ Id: data.Id ?? 0 });
    if (data.CreatedAt !== undefined) this.CreatedAt = data.CreatedAt;
    if (data.EventTypeEnum !== undefined) this.EventTypeEnum = data.EventTypeEnum;
    if (data.Id !== undefined) this.Id = data.Id;
    if (data.PayloadJSON !== undefined) this.PayloadJSON = data.PayloadJSON;
    if (data.ServerId !== undefined) this.ServerId = data.ServerId;
    if (data.UserId !== undefined) this.UserId = data.UserId;
  }
}

export interface GameDataModel {
  DataSheetId: number;
  GameId: number;
  Id: number;
  Message: MultiLingualString;
  Response: MultiLingualString;
}

export enum GameDataModelFieldEnum {
  DataSheetId = "DataSheetId",
  GameId = "GameId",
  Id = "Id",
  Message = "Message",
  Response = "Response"
}

export function getGameDataFieldType(field: GameDataModelFieldEnum): BaseEntityFieldType {
  switch (field) {
    case GameDataModelFieldEnum.DataSheetId:
      return BaseEntityFieldType.Number;
    case GameDataModelFieldEnum.GameId:
      return BaseEntityFieldType.Number;
    case GameDataModelFieldEnum.Id:
      return BaseEntityFieldType.Number;
    case GameDataModelFieldEnum.Message:
      return BaseEntityFieldType.MultiLingualString;
    case GameDataModelFieldEnum.Response:
      return BaseEntityFieldType.MultiLingualString;
  }
}

export class GameDataModel extends BaseEntityClass<GameDataModelFieldEnum> implements GameDataModel {
  protected static fieldEnum = GameDataModelFieldEnum;
  protected static tableEnum = enums.TableEnum.GAME_DATA;

  DataSheetId: number;
  GameId: number;
  Message: MultiLingualString;
  Response: MultiLingualString;

  constructor(data: Partial<GameDataModel>) {
    super(data as BaseEntity);
    this.DataSheetId = data.DataSheetId!;
    this.GameId = data.GameId!;
    this.Id = data.Id!;
    this.Message = data.Message!;
    this.Response = data.Response!;
  }
}

export interface GameDataSaveModel {
  DataSheetId?: number;
  GameId?: number;
  Id?: number;
  Message?: MultiLingualString;
  Response?: MultiLingualString;
}

export class GameDataSaveModel extends BaseEntityClass<GameDataModelFieldEnum> implements GameDataSaveModel {
  protected static fieldEnum = GameDataModelFieldEnum;
  protected static tableEnum = enums.TableEnum.GAME_DATA;

  DataSheetId?: number;
  GameId?: number;
  Message?: MultiLingualString;
  Response?: MultiLingualString;

  constructor(data: Partial<GameDataSaveModel>) {
    super({ Id: data.Id ?? 0 });
    if (data.DataSheetId !== undefined) this.DataSheetId = data.DataSheetId;
    if (data.GameId !== undefined) this.GameId = data.GameId;
    if (data.Id !== undefined) this.Id = data.Id;
    if (data.Message !== undefined) this.Message = data.Message;
    if (data.Response !== undefined) this.Response = data.Response;
  }
}

export interface GameTypesModel {
  allowMessageChange: boolean;
  description: number;
  gameDisabled: number;
  gameName: string;
  gameRules: number;
  Id: number;
  pointPerGame: number;
  replyMessage: boolean;
  sameUserAllowed: boolean;
}

export enum GameTypesModelFieldEnum {
  allowMessageChange = "allowMessageChange",
  description = "description",
  gameDisabled = "gameDisabled",
  gameName = "gameName",
  gameRules = "gameRules",
  Id = "Id",
  pointPerGame = "pointPerGame",
  replyMessage = "replyMessage",
  sameUserAllowed = "sameUserAllowed"
}

export function getGameTypesFieldType(field: GameTypesModelFieldEnum): BaseEntityFieldType {
  switch (field) {
    case GameTypesModelFieldEnum.allowMessageChange:
      return BaseEntityFieldType.Boolean;
    case GameTypesModelFieldEnum.description:
      return BaseEntityFieldType.Number;
    case GameTypesModelFieldEnum.gameDisabled:
      return BaseEntityFieldType.Number;
    case GameTypesModelFieldEnum.gameName:
      return BaseEntityFieldType.String;
    case GameTypesModelFieldEnum.gameRules:
      return BaseEntityFieldType.Number;
    case GameTypesModelFieldEnum.Id:
      return BaseEntityFieldType.Number;
    case GameTypesModelFieldEnum.pointPerGame:
      return BaseEntityFieldType.Number;
    case GameTypesModelFieldEnum.replyMessage:
      return BaseEntityFieldType.Boolean;
    case GameTypesModelFieldEnum.sameUserAllowed:
      return BaseEntityFieldType.Boolean;
  }
}

export interface GamesModel {
  Answer: string;
  ChannelId: string;
  GameTypeEnum: enums.GameTypeEnum;
  Id: number;
  LastUser: string;
  MessageId: string;
  ServerId: string;
  Settings: Games_Settings;
}

export enum GamesModelFieldEnum {
  Answer = "Answer",
  ChannelId = "ChannelId",
  GameTypeEnum = "GameTypeEnum",
  Id = "Id",
  LastUser = "LastUser",
  MessageId = "MessageId",
  ServerId = "ServerId",
  Settings = "Settings"
}

export function getGamesFieldType(field: GamesModelFieldEnum): BaseEntityFieldType {
  switch (field) {
    case GamesModelFieldEnum.Answer:
      return BaseEntityFieldType.String;
    case GamesModelFieldEnum.ChannelId:
      return BaseEntityFieldType.String;
    case GamesModelFieldEnum.GameTypeEnum:
      return BaseEntityFieldType.Enum;
    case GamesModelFieldEnum.Id:
      return BaseEntityFieldType.Number;
    case GamesModelFieldEnum.LastUser:
      return BaseEntityFieldType.String;
    case GamesModelFieldEnum.MessageId:
      return BaseEntityFieldType.String;
    case GamesModelFieldEnum.ServerId:
      return BaseEntityFieldType.String;
    case GamesModelFieldEnum.Settings:
      return BaseEntityFieldType.Json;
  }
}

export class GamesModel extends BaseEntityClass<GamesModelFieldEnum> implements GamesModel {
  protected static fieldEnum = GamesModelFieldEnum;
  protected static tableEnum = enums.TableEnum.GAMES;

  Answer: string;
  ChannelId: string;
  GameTypeEnum: enums.GameTypeEnum;
  LastUser: string;
  MessageId: string;
  ServerId: string;
  Settings: Games_Settings;

  constructor(data: Partial<GamesModel>) {
    super(data as BaseEntity);
    this.Answer = data.Answer!;
    this.ChannelId = data.ChannelId!;
    this.GameTypeEnum = data.GameTypeEnum!;
    this.Id = data.Id!;
    this.LastUser = data.LastUser!;
    this.MessageId = data.MessageId!;
    this.ServerId = data.ServerId!;
    this.Settings = data.Settings!;
  }
}

export interface GamesSaveModel {
  Answer?: string;
  ChannelId?: string;
  GameTypeEnum?: enums.GameTypeEnum;
  Id?: number;
  LastUser?: string;
  MessageId?: string;
  ServerId?: string;
  SettingsJSON?: Games_Settings;
}

export class GamesSaveModel extends BaseEntityClass<GamesModelFieldEnum> implements GamesSaveModel {
  protected static fieldEnum = GamesModelFieldEnum;
  protected static tableEnum = enums.TableEnum.GAMES;
  protected static fieldToPropertyMap: Record<string, string> = { Settings: "SettingsJSON" };

  Answer?: string;
  ChannelId?: string;
  GameTypeEnum?: enums.GameTypeEnum;
  LastUser?: string;
  MessageId?: string;
  ServerId?: string;
  SettingsJSON?: Games_Settings;

  constructor(data: Partial<GamesSaveModel>) {
    super({ Id: data.Id ?? 0 });
    if (data.Answer !== undefined) this.Answer = data.Answer;
    if (data.ChannelId !== undefined) this.ChannelId = data.ChannelId;
    if (data.GameTypeEnum !== undefined) this.GameTypeEnum = data.GameTypeEnum;
    if (data.Id !== undefined) this.Id = data.Id;
    if (data.LastUser !== undefined) this.LastUser = data.LastUser;
    if (data.MessageId !== undefined) this.MessageId = data.MessageId;
    if (data.ServerId !== undefined) this.ServerId = data.ServerId;
    if (data.SettingsJSON !== undefined) this.SettingsJSON = data.SettingsJSON;
  }
}

export interface LanguageModel {
  EN: string;
  ES: string;
  GE: string;
  Id: number;
  NL: string;
}

export enum LanguageModelFieldEnum {
  EN = "EN",
  ES = "ES",
  GE = "GE",
  Id = "Id",
  NL = "NL"
}

export function getLanguageFieldType(field: LanguageModelFieldEnum): BaseEntityFieldType {
  switch (field) {
    case LanguageModelFieldEnum.EN:
      return BaseEntityFieldType.String;
    case LanguageModelFieldEnum.ES:
      return BaseEntityFieldType.String;
    case LanguageModelFieldEnum.GE:
      return BaseEntityFieldType.String;
    case LanguageModelFieldEnum.Id:
      return BaseEntityFieldType.Number;
    case LanguageModelFieldEnum.NL:
      return BaseEntityFieldType.String;
  }
}

export interface MetricsModel {
  Date: Date;
  Id: number;
  Metrics: Metrics_Metrics;
}

export enum MetricsModelFieldEnum {
  Date = "Date",
  Id = "Id",
  Metrics = "Metrics"
}

export function getMetricsFieldType(field: MetricsModelFieldEnum): BaseEntityFieldType {
  switch (field) {
    case MetricsModelFieldEnum.Date:
      return BaseEntityFieldType.Date;
    case MetricsModelFieldEnum.Id:
      return BaseEntityFieldType.Number;
    case MetricsModelFieldEnum.Metrics:
      return BaseEntityFieldType.Json;
  }
}

export class MetricsModel extends BaseEntityClass<MetricsModelFieldEnum> implements MetricsModel {
  protected static fieldEnum = MetricsModelFieldEnum;
  protected static tableEnum = enums.TableEnum.METRICS;

  Date: Date;
  Metrics: Metrics_Metrics;

  constructor(data: Partial<MetricsModel>) {
    super(data as BaseEntity);
    this.Date = data.Date!;
    this.Id = data.Id!;
    this.Metrics = data.Metrics!;
  }
}

export interface MetricsSaveModel {
  Date?: Date;
  Id?: number;
  MetricsJSON?: Metrics_Metrics;
}

export class MetricsSaveModel extends BaseEntityClass<MetricsModelFieldEnum> implements MetricsSaveModel {
  protected static fieldEnum = MetricsModelFieldEnum;
  protected static tableEnum = enums.TableEnum.METRICS;
  protected static fieldToPropertyMap: Record<string, string> = { Metrics: "MetricsJSON" };

  Date?: Date;
  MetricsJSON?: Metrics_Metrics;

  constructor(data: Partial<MetricsSaveModel>) {
    super({ Id: data.Id ?? 0 });
    if (data.Date !== undefined) this.Date = data.Date;
    if (data.Id !== undefined) this.Id = data.Id;
    if (data.MetricsJSON !== undefined) this.MetricsJSON = data.MetricsJSON;
  }
}

export interface PointsModel {
  GameId: number;
  Id: number;
  Points: number;
  ServerId: string;
  UserId: string;
}

export enum PointsModelFieldEnum {
  GameId = "GameId",
  Id = "Id",
  Points = "Points",
  ServerId = "ServerId",
  UserId = "UserId"
}

export function getPointsFieldType(field: PointsModelFieldEnum): BaseEntityFieldType {
  switch (field) {
    case PointsModelFieldEnum.GameId:
      return BaseEntityFieldType.Number;
    case PointsModelFieldEnum.Id:
      return BaseEntityFieldType.Number;
    case PointsModelFieldEnum.Points:
      return BaseEntityFieldType.Number;
    case PointsModelFieldEnum.ServerId:
      return BaseEntityFieldType.String;
    case PointsModelFieldEnum.UserId:
      return BaseEntityFieldType.String;
  }
}

export class PointsModel extends BaseEntityClass<PointsModelFieldEnum> implements PointsModel {
  protected static fieldEnum = PointsModelFieldEnum;
  protected static tableEnum = enums.TableEnum.POINTS;

  GameId: number;
  Points: number;
  ServerId: string;
  UserId: string;

  constructor(data: Partial<PointsModel>) {
    super(data as BaseEntity);
    this.GameId = data.GameId!;
    this.Id = data.Id!;
    this.Points = data.Points!;
    this.ServerId = data.ServerId!;
    this.UserId = data.UserId!;
  }
}

export interface PointsSaveModel {
  GameId?: number;
  Id?: number;
  Points?: number;
  ServerId?: string;
  UserId?: string;
}

export class PointsSaveModel extends BaseEntityClass<PointsModelFieldEnum> implements PointsSaveModel {
  protected static fieldEnum = PointsModelFieldEnum;
  protected static tableEnum = enums.TableEnum.POINTS;

  GameId?: number;
  Points?: number;
  ServerId?: string;
  UserId?: string;

  constructor(data: Partial<PointsSaveModel>) {
    super({ Id: data.Id ?? 0 });
    if (data.GameId !== undefined) this.GameId = data.GameId;
    if (data.Id !== undefined) this.Id = data.Id;
    if (data.Points !== undefined) this.Points = data.Points;
    if (data.ServerId !== undefined) this.ServerId = data.ServerId;
    if (data.UserId !== undefined) this.UserId = data.UserId;
  }
}

export interface ServersModel {
  Id: number;
  LanguageEnum: enums.LanguageEnum;
  MemberCount: number;
  Name: string;
  Points: number;
  ServerId: string;
}

export enum ServersModelFieldEnum {
  Id = "Id",
  LanguageEnum = "LanguageEnum",
  MemberCount = "MemberCount",
  Name = "Name",
  Points = "Points",
  ServerId = "ServerId"
}

export function getServersFieldType(field: ServersModelFieldEnum): BaseEntityFieldType {
  switch (field) {
    case ServersModelFieldEnum.Id:
      return BaseEntityFieldType.Number;
    case ServersModelFieldEnum.LanguageEnum:
      return BaseEntityFieldType.Enum;
    case ServersModelFieldEnum.MemberCount:
      return BaseEntityFieldType.Number;
    case ServersModelFieldEnum.Name:
      return BaseEntityFieldType.String;
    case ServersModelFieldEnum.Points:
      return BaseEntityFieldType.Number;
    case ServersModelFieldEnum.ServerId:
      return BaseEntityFieldType.String;
  }
}

export class ServersModel extends BaseEntityClass<ServersModelFieldEnum> implements ServersModel {
  protected static fieldEnum = ServersModelFieldEnum;
  protected static tableEnum = enums.TableEnum.SERVERS;

  LanguageEnum: enums.LanguageEnum;
  MemberCount: number;
  Name: string;
  Points: number;
  ServerId: string;

  constructor(data: Partial<ServersModel>) {
    super(data as BaseEntity);
    this.Id = data.Id!;
    this.LanguageEnum = data.LanguageEnum!;
    this.MemberCount = data.MemberCount!;
    this.Name = data.Name!;
    this.Points = data.Points!;
    this.ServerId = data.ServerId!;
  }
}

export interface ServersSaveModel {
  Id?: number;
  LanguageEnum?: enums.LanguageEnum;
  MemberCount?: number;
  Name?: string;
  Points?: number;
  ServerId?: string;
}

export class ServersSaveModel extends BaseEntityClass<ServersModelFieldEnum> implements ServersSaveModel {
  protected static fieldEnum = ServersModelFieldEnum;
  protected static tableEnum = enums.TableEnum.SERVERS;

  LanguageEnum?: enums.LanguageEnum;
  MemberCount?: number;
  Name?: string;
  Points?: number;
  ServerId?: string;

  constructor(data: Partial<ServersSaveModel>) {
    super({ Id: data.Id ?? 0 });
    if (data.Id !== undefined) this.Id = data.Id;
    if (data.LanguageEnum !== undefined) this.LanguageEnum = data.LanguageEnum;
    if (data.MemberCount !== undefined) this.MemberCount = data.MemberCount;
    if (data.Name !== undefined) this.Name = data.Name;
    if (data.Points !== undefined) this.Points = data.Points;
    if (data.ServerId !== undefined) this.ServerId = data.ServerId;
  }
}

export interface StatisticsModel {
  Date: Date;
  GameId: number;
  Id: number;
  Value: number;
}

export enum StatisticsModelFieldEnum {
  Date = "Date",
  GameId = "GameId",
  Id = "Id",
  Value = "Value"
}

export function getStatisticsFieldType(field: StatisticsModelFieldEnum): BaseEntityFieldType {
  switch (field) {
    case StatisticsModelFieldEnum.Date:
      return BaseEntityFieldType.Date;
    case StatisticsModelFieldEnum.GameId:
      return BaseEntityFieldType.Number;
    case StatisticsModelFieldEnum.Id:
      return BaseEntityFieldType.Number;
    case StatisticsModelFieldEnum.Value:
      return BaseEntityFieldType.Number;
  }
}

export interface TableEnumsModel {
  Id: number;
  TableName: string;
}

export enum TableEnumsModelFieldEnum {
  Id = "Id",
  TableName = "TableName"
}

export function getTableEnumsFieldType(field: TableEnumsModelFieldEnum): BaseEntityFieldType {
  switch (field) {
    case TableEnumsModelFieldEnum.Id:
      return BaseEntityFieldType.Number;
    case TableEnumsModelFieldEnum.TableName:
      return BaseEntityFieldType.String;
  }
}

export interface TimelineEntriesModel {
  Changes: TimelineEntries_Changes;
  CreatedAt: Date;
  Id: number;
  ObjectId: number;
  ServerId: number;
  TableEnum: enums.TableEnum;
  TimelineType: number;
  UserId: number;
}

export enum TimelineEntriesModelFieldEnum {
  Changes = "Changes",
  CreatedAt = "CreatedAt",
  Id = "Id",
  ObjectId = "ObjectId",
  ServerId = "ServerId",
  TableEnum = "TableEnum",
  TimelineType = "TimelineType",
  UserId = "UserId"
}

export function getTimelineEntriesFieldType(field: TimelineEntriesModelFieldEnum): BaseEntityFieldType {
  switch (field) {
    case TimelineEntriesModelFieldEnum.Changes:
      return BaseEntityFieldType.Json;
    case TimelineEntriesModelFieldEnum.CreatedAt:
      return BaseEntityFieldType.Date;
    case TimelineEntriesModelFieldEnum.Id:
      return BaseEntityFieldType.Number;
    case TimelineEntriesModelFieldEnum.ObjectId:
      return BaseEntityFieldType.Number;
    case TimelineEntriesModelFieldEnum.ServerId:
      return BaseEntityFieldType.Number;
    case TimelineEntriesModelFieldEnum.TableEnum:
      return BaseEntityFieldType.Enum;
    case TimelineEntriesModelFieldEnum.TimelineType:
      return BaseEntityFieldType.Number;
    case TimelineEntriesModelFieldEnum.UserId:
      return BaseEntityFieldType.Number;
  }
}

export class TimelineEntriesModel extends BaseEntityClass<TimelineEntriesModelFieldEnum> implements TimelineEntriesModel {
  protected static fieldEnum = TimelineEntriesModelFieldEnum;
  protected static tableEnum = enums.TableEnum.TIMELINE_ENTRIES;

  Changes: TimelineEntries_Changes;
  CreatedAt: Date;
  ObjectId: number;
  ServerId: number;
  TableEnum: enums.TableEnum;
  TimelineType: number;
  UserId: number;

  constructor(data: Partial<TimelineEntriesModel>) {
    super(data as BaseEntity);
    this.Changes = data.Changes!;
    this.CreatedAt = data.CreatedAt!;
    this.Id = data.Id!;
    this.ObjectId = data.ObjectId!;
    this.ServerId = data.ServerId!;
    this.TableEnum = data.TableEnum!;
    this.TimelineType = data.TimelineType!;
    this.UserId = data.UserId!;
  }
}

export interface TimelineEntriesSaveModel {
  ChangesJSON?: TimelineEntries_Changes;
  CreatedAt?: Date;
  Id?: number;
  ObjectId?: number;
  ServerId?: number;
  TableEnum?: enums.TableEnum;
  TimelineType?: number;
  UserId?: number;
}

export class TimelineEntriesSaveModel extends BaseEntityClass<TimelineEntriesModelFieldEnum> implements TimelineEntriesSaveModel {
  protected static fieldEnum = TimelineEntriesModelFieldEnum;
  protected static tableEnum = enums.TableEnum.TIMELINE_ENTRIES;
  protected static fieldToPropertyMap: Record<string, string> = { Changes: "ChangesJSON" };

  ChangesJSON?: TimelineEntries_Changes;
  CreatedAt?: Date;
  ObjectId?: number;
  ServerId?: number;
  TableEnum?: enums.TableEnum;
  TimelineType?: number;
  UserId?: number;

  constructor(data: Partial<TimelineEntriesSaveModel>) {
    super({ Id: data.Id ?? 0 });
    if (data.ChangesJSON !== undefined) this.ChangesJSON = data.ChangesJSON;
    if (data.CreatedAt !== undefined) this.CreatedAt = data.CreatedAt;
    if (data.Id !== undefined) this.Id = data.Id;
    if (data.ObjectId !== undefined) this.ObjectId = data.ObjectId;
    if (data.ServerId !== undefined) this.ServerId = data.ServerId;
    if (data.TableEnum !== undefined) this.TableEnum = data.TableEnum;
    if (data.TimelineType !== undefined) this.TimelineType = data.TimelineType;
    if (data.UserId !== undefined) this.UserId = data.UserId;
  }
}

export interface UsersModel {
  CreatedAt: Date;
  Id: number;
  UserId: string;
  Username: string;
  UserRoleEnum: enums.UserRoleEnum;
}

export enum UsersModelFieldEnum {
  CreatedAt = "CreatedAt",
  Id = "Id",
  UserId = "UserId",
  Username = "Username",
  UserRoleEnum = "UserRoleEnum"
}

export function getUsersFieldType(field: UsersModelFieldEnum): BaseEntityFieldType {
  switch (field) {
    case UsersModelFieldEnum.CreatedAt:
      return BaseEntityFieldType.Date;
    case UsersModelFieldEnum.Id:
      return BaseEntityFieldType.Number;
    case UsersModelFieldEnum.UserId:
      return BaseEntityFieldType.String;
    case UsersModelFieldEnum.Username:
      return BaseEntityFieldType.String;
    case UsersModelFieldEnum.UserRoleEnum:
      return BaseEntityFieldType.Enum;
  }
}

export class UsersModel extends BaseEntityClass<UsersModelFieldEnum> implements UsersModel {
  protected static fieldEnum = UsersModelFieldEnum;
  protected static tableEnum = enums.TableEnum.USERS;

  CreatedAt: Date;
  UserId: string;
  Username: string;
  UserRoleEnum: enums.UserRoleEnum;

  constructor(data: Partial<UsersModel>) {
    super(data as BaseEntity);
    this.CreatedAt = data.CreatedAt!;
    this.Id = data.Id!;
    this.UserId = data.UserId!;
    this.Username = data.Username!;
    this.UserRoleEnum = data.UserRoleEnum!;
  }
}

export interface UsersSaveModel {
  CreatedAt?: Date;
  Id?: number;
  UserId?: string;
  Username?: string;
  UserRoleEnum?: enums.UserRoleEnum;
}

export class UsersSaveModel extends BaseEntityClass<UsersModelFieldEnum> implements UsersSaveModel {
  protected static fieldEnum = UsersModelFieldEnum;
  protected static tableEnum = enums.TableEnum.USERS;

  CreatedAt?: Date;
  UserId?: string;
  Username?: string;
  UserRoleEnum?: enums.UserRoleEnum;

  constructor(data: Partial<UsersSaveModel>) {
    super({ Id: data.Id ?? 0 });
    if (data.CreatedAt !== undefined) this.CreatedAt = data.CreatedAt;
    if (data.Id !== undefined) this.Id = data.Id;
    if (data.UserId !== undefined) this.UserId = data.UserId;
    if (data.Username !== undefined) this.Username = data.Username;
    if (data.UserRoleEnum !== undefined) this.UserRoleEnum = data.UserRoleEnum;
  }
}

